name: Invitation Request to Join GitHub Community Organization
description: Request an invitation to join the Magic-Academy GitHub Community Organization.
labels:
  - invitation-request

body:
  - type: input
    id: username
    label: 'GitHub Username'
    description: 'Please provide your GitHub username so we can send you an invitation.'
    required: true

  - type: textarea
    id: reason
    label: 'Reason for Joining'
    description: 'Tell us why you would like to join the community. This is optional but helps us understand your interest better.'
    required: false

  - type: checkboxes
    id: confirm
    label: 'I agree to the terms of joining the Magic-Academy GitHub Community.'
    required: true
    options:
      - 'Yes'
